# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install system dependencies if any
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the project files
COPY . /app

# Upgrade pip and install hatchling
RUN pip install --no-cache-dir --upgrade pip hatchling

# Install the package in editable mode
RUN pip install -e .

CMD ["python", "testrail_mcp/main.py"]
